/**
 * Pure render core for the docs config-table generator. Turns a draft-07 JSON
 * Schema (from {@link toConfigJsonSchema}) into the markdown tables committed
 * under `docs/_generated/config/`. Kept here, not in the `scripts/` generator,
 * so the rendering is unit-testable against oracle schemas and can never drift
 * from the shape the web AutoForm renders. No I/O — the impure shell (fs, argv,
 * process) lives in `scripts/docs/gen-config-tables.ts`.
 *
 * Each row carries six columns. Four are derived from the schema (setting, what
 * it is, accepted values, default) so they cannot go stale. The last two — when
 * to change it, what to expect — are judgement the schema cannot express; they
 * come from a per-schema note map the generator supplies, and the generator
 * refuses to emit a table whose note keys do not exactly match the schema's
 * leaves. That is what stops a new config field shipping undocumented.
 */
import {
  applyJsonSchemaDefaults,
  buildFormFieldsFromJsonSchema,
  type FormField,
} from './form-builder.js';

export const BANNER =
  '<!-- GENERATED by scripts/docs/gen-config-tables.ts — do not edit by hand; run `bun run docs:gen`. -->';

/** Operator guidance for one field, authored alongside the generator. */
export interface FieldNote {
  /** The situation that should make an operator reach for this setting. */
  readonly when: string;
  /** The observable consequence of changing it, including the downside. */
  readonly expect: string;
}

export type FieldNotes = Readonly<Record<string, FieldNote>>;

export interface Row {
  label: string;
  field: string;
  def: string;
  desc: string;
  values: string;
  when: string;
  expect: string;
}

const prettyPath = (p: string): string => p.replace(/\.\$item/g, '[]');

const getByPath = (obj: unknown, path: string): unknown => {
  if (path.includes('$item')) return undefined; // array element defaults live under []
  let cur: unknown = obj;
  for (const seg of path.split('.')) {
    if (cur && typeof cur === 'object' && seg in (cur as Record<string, unknown>)) {
      cur = (cur as Record<string, unknown>)[seg];
    } else return undefined;
  }
  return cur;
};

export const renderDefault = (v: unknown, required: boolean): string => {
  if (v === undefined) return required ? '_required_' : '—';
  if (v === null) return '`null`';
  if (Array.isArray(v)) return v.length === 0 ? '`[]`' : `\`${JSON.stringify(v)}\``;
  if (typeof v === 'object') return '—';
  if (typeof v === 'string') return v === '' ? '`""`' : `\`${v}\``;
  return `\`${String(v)}\``;
};

/**
 * Table cells are pipe-delimited and single-line, so neither may survive.
 * `@handle` is wrapped in a code span because GitLab resolves a bare one to a
 * user on its own instance, rewriting the text into a link nobody authored. The
 * source `.describe()` stays plain: the web form renders it as text, so a
 * backtick there would surface literally in the operator's UI.
 * Exported because the env-var table in `scripts/docs/gen-config-tables.ts`
 * renders into the same generated docs and must escape identically.
 */
export const cell = (s: string): string =>
  s
    .replace(/\r?\n/g, ' ')
    .replace(/\|/g, '\\|')
    .replace(/\s+/g, ' ')
    .replace(/(^|[^`\w])@(\w+)/g, '$1`@$2`')
    .trim() || '—';

/** What the field means, from the same `.describe()` the form tooltip shows. */
const describe = (f: FormField): string =>
  cell(f.advanced ? `${f.description ?? ''} _(advanced)_` : (f.description ?? ''));

/**
 * The accepted range, split out of the description so a reader can scan "what
 * may I type here" without reading prose. Enum options and numeric bounds are
 * the only constraints the form builder surfaces.
 */
const values = (f: FormField): string => {
  if (f.kind === 'enum') return cell(f.options.map((o) => `\`${o}\``).join(', '));
  if (f.kind === 'boolean') return 'on / off';
  if (f.kind === 'number') {
    const b: string[] = [];
    if (f.minimum !== undefined) b.push(`min ${f.minimum}`);
    if (f.exclusiveMinimum !== undefined) b.push(`> ${f.exclusiveMinimum}`);
    if (f.maximum !== undefined) b.push(`max ${f.maximum}`);
    if (f.exclusiveMaximum !== undefined) b.push(`< ${f.exclusiveMaximum}`);
    return b.length ? cell(`number, ${b.join(', ')}`) : 'number';
  }
  return 'text';
};

/** Flatten a field subtree into leaf rows, pulling defaults from `defaults`. */
const collectLeaves = (
  f: FormField,
  defaults: unknown,
  notes: FieldNotes,
  rows: Row[],
  paths: string[],
): void => {
  if (f.kind === 'object') {
    for (const c of f.fields) collectLeaves(c, defaults, notes, rows, paths);
    return;
  }
  if (f.kind === 'array' && f.element.kind === 'object') {
    for (const c of f.element.fields) collectLeaves(c, defaults, notes, rows, paths);
    return;
  }
  // Scalar leaf OR array-of-scalars: one row for the field itself. Descending
  // into a scalar element would drop the field's label/required/default and
  // emit an anonymous `$item` row.
  // A legitimate `null` default must survive: `?? f.defaultValue` would treat
  // it as missing and fall through. Only a genuinely absent (undefined) merged
  // default falls back to the field-node default.
  const resolved = getByPath(defaults, f.path);
  const def = resolved === undefined ? f.defaultValue : resolved;
  const key = prettyPath(f.path);
  const note = notes[key];
  paths.push(key);
  rows.push({
    label: f.label,
    field: key,
    def: renderDefault(def, f.required),
    desc: describe(f),
    values: values(f),
    when: cell(note?.when ?? ''),
    expect: cell(note?.expect ?? ''),
  });
};

const HEAD =
  '| Setting | What it is | Values | Default | When to change it | What to expect |\n' +
  '| --- | --- | --- | --- | --- | --- |\n';

const table = (rows: Row[]): string =>
  HEAD +
  rows
    .map(
      (r) =>
        `| \`${r.field}\`<br/>${r.label} | ${r.desc} | ${r.values} | ${r.def} | ${r.when} | ${r.expect} |`,
    )
    .join('\n') +
  '\n';

/**
 * Render one schema's partial: a table per top-level panel, mirroring the UI.
 * Returns the markdown alongside every leaf path it emitted, so the caller can
 * assert the note map covers exactly those fields.
 */
export const renderSchemaWithPaths = (
  jsonSchema: unknown,
  notes: FieldNotes = {},
): { markdown: string; paths: readonly string[] } => {
  const fields = buildFormFieldsFromJsonSchema(jsonSchema);
  const defaults = applyJsonSchemaDefaults(jsonSchema, {});
  const isPanel = (f: FormField): boolean =>
    f.kind === 'object' || (f.kind === 'array' && f.element.kind === 'object');

  const paths: string[] = [];
  let out = '';
  const coreRows: Row[] = [];
  for (const f of fields) if (!isPanel(f)) collectLeaves(f, defaults, notes, coreRows, paths);
  if (coreRows.length) out += `**Core settings**\n\n${table(coreRows)}\n`;

  for (const f of fields) {
    if (!isPanel(f)) continue;
    const rows: Row[] = [];
    collectLeaves(f, defaults, notes, rows, paths);
    if (rows.length) out += `**${f.label}**\n\n${table(rows)}\n`;
  }
  return { markdown: out, paths };
};

/** Discovery's master `enabled` switch is owned by the page toggle, stripped from the form. */
export const stripEnabled = (json: Record<string, unknown>): Record<string, unknown> => {
  // JSON deep-clone: the input is always a draft-07 JSON Schema object, so this
  // is equivalent to structuredClone and needs no DOM/Node lib in this package.
  const clone = JSON.parse(JSON.stringify(json)) as Record<string, unknown>;
  const props = clone['properties'];
  if (props && typeof props === 'object') delete (props as Record<string, unknown>)['enabled'];
  if (Array.isArray(clone['required'])) {
    clone['required'] = (clone['required'] as string[]).filter((k) => k !== 'enabled');
  }
  return clone;
};
