#!/usr/bin/env bash
if [ "${PROMTOOL_CURL_FAIL:-0}" = '1' ]; then exit 22; fi
output=''
while [ "$#" -gt 0 ]; do
  if [ "$1" = '-o' ]; then
    output="$2"
    shift 2
  else
    shift
  fi
done
cp "${PROMTOOL_DOWNLOAD_ARCHIVE:?}" "${output:?}"
