-- Discard equity snapshots whose realised leg was summed across quote assets.
--
-- The realised-P/L aggregates in `trade_archive` filtered on profile and window but never on `quote_asset`, so `equity_snapshots.realized_net_quote` was the sum of EVERY cycle the profile had ever closed, whatever currency it settled in. A profile whose `quote_asset` was changed after it had closed cycles therefore carries rows where the realised leg is counted in the OLD quote and the position legs in the new one, added together and stamped with the new quote. Such a row is not merely mis-scaled, it is internally inconsistent: no single rate converts it back, so the values cannot be recomputed and there is nothing to repair.
--
-- These rows cannot be filtered out on read either, which is what separates them from the other cross-quote case. A snapshot recorded under a PREVIOUS quote is stamped with that quote and is simply omitted by the reader now that `listForProfileInRange` selects one currency; it stays on disk and becomes readable again if the operator switches back. A contaminated row is stamped with the CURRENT quote, so every reader accepts it. Deleting is the only way to stop it plotting.
--
-- `archived_at < captured_at` is the visibility bound: the cron's aggregate ran over `[epoch, now)` at capture time, so a cycle archived after the capture never entered that total and the snapshot is clean. The two timestamps come from different clocks (`captured_at` is the DB `now()`, `archived_at` a worker-side stamp), so the bound is exact only up to skew; contamination is monotone once a foreign-quote cycle exists, so skew can spare at most the first affected row.
--
-- That bound holds only for forward-archived rows, which is why backfilled ones are excluded below. The backfill pins `archived_at` to the cycle's REAL closing time on Binance rather than to its insert time, so a run today can land a row stamped months ago. Every snapshot captured since that old date would then satisfy the bound while having been computed long before the row existed, and the delete would take ten weeks of correct curve to remove the handful of points the backfill actually contaminated. There is no insert-time column to bound on instead: `archived_at` is this table's only timestamp.
--
-- KNOWN RESIDUAL, deliberately not covered, and the same trade in both directions: under-deleting leaves a wrong point on one chart, over-deleting destroys history no rerun can rebuild. First, a snapshot captured after a BACKFILLED foreign-quote row landed really was contaminated by it, and the exclusion below spares it — the alternative is the over-delete described above. Second, a snapshot can also be contaminated through its POSITION legs — an open holding in the old quote, marked at its own currency's price, which `computeEquitySnapshot` now excludes but previously summed in. Such a holding has no `trade_archive` row until its cycle closes, so this predicate cannot see it. Catching it would mean keying on `avg_entry_prices`, which records no "opened at" and would therefore delete every snapshot of any profile currently holding a foreign-quote position, including the clean ones from before it opened. That over-deletion is unrecoverable while the residual self-corrects: the holding's cycle eventually closes, writes a `trade_archive` row, and any snapshot taken after it is then reachable by this same predicate on a later pass. Trading correct history for a case that closes itself is the worse deal.
delete from equity_snapshots e
 where exists (
   select 1
     from trade_archive t
    where t.profile_id = e.profile_id
      -- Case-folded on BOTH sides, matching the reader. `trade_archive.quote_asset` carries Binance's upper casing, but this column is stamped from `profiles.quote_asset`, which this repo allows to be stored lower or mixed case. A raw compare would read `'USDT' <> 'usdt'` as a currency mismatch and delete the entire correct series of any profile that happens to store its quote in another casing — the same over-deletion the note above refuses, arriving through letters instead of through position legs.
      and upper(t.quote_asset) <> upper(e.quote_asset)
      and t.archived_at < e.captured_at
      -- A backfilled row carries the cycle's closing time in `archived_at`, so that column cannot say when the row became visible to the aggregate. Identified by its `breakdown` keys: the backfill writes `backfill:BUY`/`backfill:SELL` unconditionally, while the forward archiver writes the strategy's `intent:side` keys and never these.
      and not (t.breakdown ? 'backfill:BUY')
 );
