# Stratejiler
Bu klasöre kendi stratejinizi ekleyebilirsiniz. Dosya adı `_strategy.py` ile bitmelidir. ve aşağıdakileri içerir:

```piton
binance_trade_bot.auto_trader adresinden AutoTrader'ı içe aktar

sınıf Stratejisi(AutoTrader):

    def izci(kendi):
        # Özel izci yönteminiz

```

Ardından, `strateji` yapılandırmanızı strateji adınıza ayarlayın. Dosyanızı adlandırdıysanız `custom_strategy.py` dosyasını kullanmak istiyorsanız, yapılandırma dosyanıza `strategy=custom` ifadesini koymanız gerekir.

Stratejinizi bir alt klasöre koyabilirsiniz ve bot yine de onu bulacaktır. İsterseniz Stratejinizi başkalarıyla paylaşın, git alt modüllerini kullanmayı deneyin.

Aşağıda bazı hazır stratejiler listelenmiştir:
## `varsayılan`

## `çoklu_paralar`
Botun takılıp kalma olasılığı daha düşüktür
