name: main

on: [push, workflow_dispatch]

env:
  REGISTRY_DOMAIN: ${{ secrets.REGISTRY_DOMAIN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GIT_CI_EMAIL: ${{ secrets.GIT_CI_EMAIL }}
  GIT_CI_NAME: ${{ secrets.GIT_CI_NAME }}
  GIT_CI_USERNAME: ${{ secrets.GIT_CI_USERNAME }}
  GIT_CI_PASSWORD: ${{ secrets.GIT_CI_PASSWORD }}
  GIT_REPO_DOMAIN: ${{ secrets.GIT_REPO_DOMAIN }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    name: Build/test and push
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Testing
        run: |
          npm install
          npm run lint
          npm run test
          bash <(curl -s https://codecov.io/bash)
      - name: Bump Version (Patch)
        if:
          github.repository == 'chrisleekr/binance-trading-bot' && github.ref ==
          'refs/heads/master'
        run: |
          git config --global user.email "$GIT_CI_EMAIL"
          git config --global user.name "$GIT_CI_NAME"
          PACKAGE_VERSION=$(npm version patch -m "Update version to %s [skip ci]")
          git status
          git push https://$GIT_CI_USERNAME:$GIT_CI_PASSWORD@$GIT_REPO_DOMAIN/chrisleekr/binance-trading-bot.git HEAD:$GITHUB_REF
          git push https://$GIT_CI_USERNAME:$GIT_CI_PASSWORD@$GIT_REPO_DOMAIN/chrisleekr/binance-trading-bot.git $PACKAGE_VERSION
      - name: Build/Push production docker image
        if:
          github.repository == 'chrisleekr/binance-trading-bot' && github.ref ==
          'refs/heads/master'
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $REGISTRY_DOMAIN
          PACKAGE_VERSION=$(grep version package.json | cut -c 15- | rev | cut -c 3- | rev)
          docker build . --build-arg PACKAGE_VERSION=$PACKAGE_VERSION --build-arg NODE_ENV=production --target production-stage -t $REGISTRY_DOMAIN/chrisleekr/binance-trading-bot:latest -t $REGISTRY_DOMAIN/chrisleekr/binance-trading-bot:$PACKAGE_VERSION
          docker push $REGISTRY_DOMAIN/chrisleekr/binance-trading-bot:$PACKAGE_VERSION
          docker push $REGISTRY_DOMAIN/chrisleekr/binance-trading-bot:latest
